"""add index for price

Revision ID: 6b475979a24f
Revises: 74e8a511d695
Create Date: 2025-08-12 19:30:47.599849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b475979a24f'
down_revision: Union[str, Sequence[str], None] = '74e8a511d695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_price'), table_name='products')
    # ### end Alembic commands ###
