"""added_column_title_price_for_orderitem

Revision ID: b95049532e3a
Revises: 7472b06fea9c
Create Date: 2025-09-06 11:26:25.073300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95049532e3a'
down_revision: Union[str, Sequence[str], None] = '7472b06fea9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_title', sa.String(length=100), nullable=False))
    op.add_column('order_items', sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_price')
    op.drop_column('order_items', 'product_title')
    # ### end Alembic commands ###
