"""added_colomn_reserved_for_product

Revision ID: e68897dd5cec
Revises: 55ee91a2097e
Create Date: 2025-09-05 11:49:24.234757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68897dd5cec'
down_revision: Union[str, Sequence[str], None] = '55ee91a2097e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reserved', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reserved')
    # ### end Alembic commands ###
